name: build

on:
  workflow_dispatch:
  push: { paths: [.github/workflows/build.yaml] }

jobs:
  info:
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.info.outputs.version }}
      release_version: ${{ steps.info.outputs.release_version }}

    steps:
    - uses: actions/checkout@v2
      with: { submodules : recursive, fetch-depth: 0 }

    - id: info
      run: |
        git fetch --tags --force
        echo "::set-output name=version::$(git describe --always --tags)"
        echo "::set-output name=release_version::$(git describe --tags --exact-match --exclude latest 2>/dev/null)"
      working-directory: lua-language-server

    # Version Info

    - run: 'git log -1 --date=iso --format="{ \"date\": \"%cd\", \"commit\": \"%H\" }" > ../version.json'
      working-directory: 'lua-language-server/'
      continue-on-error: true

    - run: |
        jq '. | .version="${{ steps.info.outputs.version }}"' ../version.json > ../version.json.bak && mv ../version.json{.bak,}
      working-directory: 'lua-language-server/'
      continue-on-error: true

    - run: jq -C . version.json
      continue-on-error: true

    - run: |
       ./.github/scripts/get_release_note.sh > release.txt
       cat release.txt

    - uses: actions/upload-artifact@v2
      with:
        name: info
        path: version.json
        retention-days: 1

    - uses: actions/upload-artifact@v2
      with:
        name: info
        path: release.txt
        retention-days: 1

  compile:
    needs: [info]

    runs-on: '${{ matrix.os }}'

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
      with: { submodules : recursive }
    - uses: actions/download-artifact@v2

    - uses: actboy168/setup-luamake@master

    # Build

    - if: runner.os != 'Linux'
      run: luamake
      working-directory: 'lua-language-server/'

    - if: runner.os == 'Linux'
      run: luamake -gcc gcc-8 -gxx g++-8
      working-directory: 'lua-language-server/'

    # Clean up

    - run: |
        rm -r build
        chmod +x bin/*/lua-language-server
        cp ../info/version.json .
      working-directory: 'lua-language-server/'

    # Create Artifact

    - run: |
        tar cfz lua-language-server-${{ matrix.os }}.tar.gz lua-language-server

    - uses: actions/upload-artifact@v2
      with:
        name: build
        path: lua-language-server-${{ matrix.os }}.tar.gz
        retention-days: 1

  publish:
    needs: [compile, info]

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        type: [ latest, version ]

    steps:
      - uses: actions/download-artifact@v2

      - if: matrix.type == 'latest'
        run: |
          echo 'TAG_NAME=latest' >> $GITHUB_ENV
          echo 'SUBJECT=lua-language-server@${{ needs.info.outputs.version }}' >> $GITHUB_ENV

      - if: matrix.type == 'version' && needs.info.outputs.release_version != ''
        run: |
          echo 'TAG_NAME=${{ needs.info.outputs.release_version }}' >> $GITHUB_ENV
          echo 'SUBJECT=lua-language-server@${{ needs.info.outputs.release_version }}' >> $GITHUB_ENV

      - if: matrix.type == 'latest'
        uses: dev-drprasad/delete-tag-and-release@v0.1.2
        env:  { GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}' }
        with: { delete_release: false, tag_name: latest }

      - run: |
          echo "RELEASE_BODY<<EOF" >> $GITHUB_ENV
          cat ./info/release.txt >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - if: env.TAG_NAME != ''
        uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.TAG_NAME }}
          name: ${{ env.SUBJECT }}
          prerelease: ${{ env.TAG_NAME == 'latest' }}
          body: ${{ env.RELEASE_BODY }}
          commitish: ${{ github.sha }}
          gzip: false
          allow_override: true
          files: |
            lua-language-server-macos.tar.gz:./build/lua-language-server-macos-latest.tar.gz
            lua-language-server-linux.tar.gz:./build/lua-language-server-ubuntu-latest.tar.gz
            lua-language-server-windows.tar.gz:./build/lua-language-server-windows-latest.tar.gz
            version.json:./info/version.json

