name: update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'
  push: { paths: [.github/workflows/update.yaml] }

jobs:
  update:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - run: |
        git submodule update --init --remote
        git status --short || test $? = 1
        echo "HAS_CHANGES=$(git status --short | grep 'lua-language-server' || test $? = 1)" >> $GITHUB_ENV

    - run: |
        git fetch --tags --force
        echo "DESCRIBE=$(git describe --always --tags)" >> $GITHUB_ENV
        echo "DESCRIBE_TAG=$(git describe --tags --exact-match --exclude latest 2>/dev/null)" >> $GITHUB_ENV
      working-directory: lua-language-server

    - if: env.HAS_CHANGES != '' && env.DESCRIBE_TAG != ''
      run: |
        echo "COMMIT_TAG=${{ env.DESCRIBE_TAG }} --force" >> $GITHUB_ENV
      working-directory: lua-language-server

    - if: env.HAS_CHANGES != ''
      uses: EndBug/add-and-commit@v5
      with:
        add: 'lua-language-server'
        push: true
        author_name:  Github action
        author_email: josa@gesell.me
        message: 'sumneko/lua-language-server: ${{ env.DESCRIBE }}'
        tag: '${{ env.COMMIT_TAG }}'
      env:
        GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

    - if: env.HAS_CHANGES != ''
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: build
        ref: master
        token: ${{ secrets.PERSONAL_TOKEN }}
